#ERROR HANDLING
#SYNTAX ERROR-COMPILE ERROR
#RUN_TIME ERROR->DURING EXECUTION TIME IT WILL HAPPENS
#LOGICAL ERROR-> ERROR IN LOGIC(IN CANT VISIBLE)

#error handling
#syntax error
'''for i in range(10)
print(i)'''

#run_time error
'''=int(input())
b=int(input())
print(a//b)'''#10/0->zero division error

#logical error
'''a=10
b=20
print(a-b)'''

''''a=10
b=20
if a>b:
    print("less")'''
